# Set update schedule for GitHub Actions and Maven dependencies
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Check for updates to Maven dependencies every day
      interval: "daily"
